---
dist: xenial

language: python
python: "3.7"

install:
  - pip install ansible

script:
  - ansible-playbook ci/prepare.yml
  - |
    cd ~/build/site &&
    ansible-playbook deploy.yml \
      --skip-tags publish \
      -e hugo_content_directory=$TRAVIS_BUILD_DIR
