---
dist: xenial

language: python
python: "3.7"

install:
  - pip install ansible

script:
  - |
    git clone --recursive https://github.com/larsks/blog.oddbit.com-ci \
      $TRAVIS_BUILD_DIR/../ci
    git clone --recursive https://github.com/larsks/blog.oddbit.com-hugo \
      $TRAVIS_BUILD_DIR/../site

  - |
    cd $TRAVIS_BUILD_DIR/../ci &&
    ansible-playbook prepare.yml

  - |
    cd $TRAVIS_BUILD_DIR/../site &&
    ansible-playbook render.yml \
      --skip-tags publish \
      -e hugo_content_directory=$TRAVIS_BUILD_DIR

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  local_dir: $TRAVIS_BUILD_DIR/../site/public
  github_token: $GITHUB_TOKEN
  repo: larsks/blog.oddbit.com
  target_branch: gh-pages
  verbose: true
  "on":
    branch: master
