#!/bin/bash
#
# usage: newpost "This is a title"

[ "$DISPLAY" ] && VISUAL=gvim

MAX_TITLE_LEN=30

while getopts 'g' ch; do
	case $ch in
		(g) post_use_git=1;;
	esac
done
shift $(( $OPTIND - 1 ))

[ "$1" ] || exit 1

title="$1"
date=$(date +%Y-%m-%d)
stub=$(tr -dc '[a-zA-Z ]' <<< $title)
stub=${stub// /-}
stub=${stub,,}
stub=${stub:0:$MAX_TITLE_LEN}
filename="${date}-${stub}.md"
branch=draft/$stub

if [[ ! -f $filename ]]; then
cat > $filename <<EOF
---
title: $title
date: $date
layout: post
tags:

---

EOF
fi

if [ "$post_use_git" = 1 ]; then
git co -b $branch posts
git push -u origin $branch
git add -N $filename
fi

exec ${VISUAL:-${EDITOR:-vi}} $filename

