#!/bin/bash
#
# usage: newpost "This is a title"

MAX_TITLE_LEN=30

[ "$1" ] || exit 1

title="$1"
date=$(date +%Y-%m-%d)
stub=$(tr -dc '[a-zA-Z ]' <<< $title)
stub=${stub// /-}
stub=${stub,,}
stub=${stub:0:$MAX_TITLE_LEN}
filename="${date}-${stub}.md"

git co -b draft/$stub posts

if [[ ! -f $filename ]]; then
cat > $filename <<EOF
---
title: $title
date: $date
layout: post
tags:

---


EOF
fi

git add -N $filename

exec ${VISUAL:-${EDITOR:-vi}} $filename

