#!/bin/sh
#
# Syntax check markdown files before committing.

set -e

git diff-index --name-only HEAD |
git checkout-index --stdin --temp | (
	retcode=0

	while read tmp actual; do
		if [ "${actual##*.}" = md ]; then
			if ! maruku -o /dev/null -b $tmp > /dev/null 2>&1; then
				echo "ERROR: $actual: markdown errors"
				retcode=1
			fi
		fi

		rm -f $tmp
	done

	exit $retcode
)

exit 0

