#!/bin/bash

MAX_TITLE_LEN=30

tags=()
while getopts d:s:t:n ch; do
	case $ch in
	(t)	tags+=($OPTARG)
	;;

	(n)	NOBRANCH=1
	;;

	(s)	stub=$OPTARG
		;;

	(d)	date=$OPTARG
		;;

	(\?)	exit 2
		;;
	esac
done
shift $(( OPTIND - 1 ))

title="$1"

if ! [[ $title ]]; then
	echo "ERROR: you must provide a title" >&2
	exit 1
fi

if [ -z "$date" ]; then
	date=$(date +%Y-%m-%d)
fi

if [ -z "$stub" ]; then
	stub=$(tr -dc '[a-zA-Z ]' <<< $title)
	stub=${stub// /-}
	stub=${stub,,}
	stub=${stub:0:$MAX_TITLE_LEN}
fi

filename="${date}-${stub}.md"
branch="drafts/${stub}"

if [ "$NOBRANCH" != 1 ]; then
	if git show-ref --verify --quiet "refs/heads/$branch"; then
		git checkout "$branch" > /dev/null
	else
		git checkout -b "$branch" master > /dev/null
	fi
fi

if [[ ! -f "$filename" ]]; then
(
cat <<EOF
---
title: "$title"
date: "$date"
layout: post
tags:
EOF

for tag in "${tags[@]}"; do
	echo "- \"$tag\""
done

cat <<EOF
---

EOF
) > "$filename"

(
git add "$filename"
git commit -m "added $filename"
) > /dev/null

fi

echo "$filename"
