#!/usr/bin/python3

import click
import datetime
import pathlib
import string
import subprocess
import sys
import yaml


@click.command()
@click.option('-t', '--tag', multiple=True)
@click.option('-M', '--max-length', default=30, type=int)
@click.option('-d', '--date')
@click.option('-s', '--stub')
@click.option('-D', '--draft', is_flag=True)
@click.option('-g', '--git', is_flag=True)
@click.option('-S', '--stdout', is_flag=True)
@click.option('-w', '--weight', type=int)
@click.option('-P', '--post-directory', default='post', type=pathlib.Path)
@click.argument('title')
def new_post(tag, max_length, date, stub, git, stdout, draft, weight,
             post_directory, title):
    metadata = {'title': title}

    if tag:
        metadata['tags'] = tag

    if weight is not None:
        metadata['weight'] = weight

    if draft:
        metadata['draft'] = True

    if date:
        metadata['date'] = date
    else:
        metadata['date'] = datetime.datetime.now().strftime('%Y-%m-%d')

    stub = ''.join(c for c in title
                   if c in string.ascii_letters + string.digits + '-_ '
                   ).replace(' ', '-').lower()[:max_length]
    stub = stub.rstrip('-')

    filename = '{}-{}.md'.format(metadata['date'], stub)
    branch = 'draft/{}'.format(stub)
    metadata['filename'] = filename
    path = post_directory / filename

    with (sys.stdout if stdout else open(path, 'w')) as fd:
        fd.write('\n'.join(['---',
                            yaml.safe_dump(metadata, default_flow_style=False),
                            '---', '', '']))

    if not stdout:
        if git:
            pipeline = [
                ['git', 'checkout', 'master'],
                ['git', 'checkout', '-B', branch],
                ['git', 'add', path],
                ['git', 'commit', '-m' 'added {}'.format(path)],
            ]

            for command in pipeline:
                subprocess.run(command, stdout=subprocess.DEVNULL)

        print(path)


if __name__ == '__main__':
    new_post()
