#!/bin/sh
#
# Syntax check markdown files before committing.

git stash -q --keep-index
trap 'git stash pop -q' EXIT

git diff-index --cached --name-only HEAD |
while read path; do
	# we only care about markdown files
	[ "${path##*.}" = md ] || continue

	md-verify-links $path || exit 1
done

exit $?

