#!/bin/sh
#
# Syntax check markdown files before committing.

rc=0
tmpdir=$(mktemp -d precommitXXXXXX)
trap "rm -rf $tmpdir" EXIT

set -e

git checkout-index -a --prefix=$tmpdir/

git diff-index --cached --name-only HEAD --diff-filter=ACMR '*.md' |
while read file; do
	if ! remark --frail --no-stdout "$file"; then
		rc=1
	fi
done

exit $rc
