on:
  push:
    branches:
      - master

jobs:
  build:
    name: Generate content
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: "0.88.0"
    steps:
      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: '^3.9'

      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: content

      - name: Check out hugo config
        uses: actions/checkout@v2
        with:
          repository: larsks/blog.oddbit.com-hugo
          path: site
          submodules: true

      - name: Check out posts
        uses: actions/checkout@v2
        with:
          repository: larsks/blog.oddbit.com
          path: posts
          ref: gh-pages
          ssh-key: ${{ secrets.BLOG_DEPLOY_KEY }}

      - name: Configure caching
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/hugo
          key: hugo-${{ runner.os }}-${{ env.HUGO_VERSION }}

      - name: Install Hugo
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl -sfL -o hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
          mkdir -p ~/hugo
          tar -C ~/hugo -xf hugo.tar.gz hugo

      - name: Build blog
        run: |
          cd site
          ~/hugo/hugo -v -e production -c ../content

      - name: Generate metadata
        run: |
          cat <<EOF > site/public/metadata.json
          {
            "date": "$(TZ=UTC date '+%Y-%m-%dT%H:%M:%SZ')",
            "content": "$(git -C content rev-parse HEAD)",
            "config": "$(git -C site rev-parse HEAD)"
          }
          EOF

      - name: Publish to gh-pages
        run: |
          rsync -a --delete --exclude=.git/ site/public/ posts/
          git -C posts config user.name 'Blog Deploy Workflow'
          git -C posts config user.email 'lars@oddbit.com'
          git -C posts add .
          git -C posts commit -m "publish blog from ${{ github.sha }}"
          git -C posts push
